"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var CallMember = sequelize.define("CallMember", {
    // id autogenerated by sequelize
    alias: { type: DataTypes.STRING },
    profilePicture: { type: DataTypes.STRING, allowNull: true }
  }, {
      classMethods:{
        associate: function(models) {
          CallMember.belongsTo(models.User);
          CallMember.belongsTo(models.Call);
        }
      }
  });

  return CallMember;
};
