"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var Channel = sequelize.define("Channel", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(50) },
    type: { type: DataTypes.ENUM('S', 'P'), defaultValue: 'S' }, //S stands for 'Shared'; P stands for 'Private'
    description: { type: DataTypes.STRING(500) },
    state: { type: DataTypes.ENUM('O', 'B', 'C'), defaultValue: 'O' },
    closedAt: { type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
    },
      classMethods:{
        associate: function(models) {
          Channel.belongsTo(models.Project);
        }
      }
    }
  );

  return Channel;
};
