"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var Channel = sequelize.define("Channel", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(50) },
    type: { type: DataTypes.ENUM('S', 'P'), defaultValue: 'S' }, //S stands for 'Shared'; P stands for 'Private'
    description: { type: DataTypes.STRING(200) },
    state: { type: DataTypes.ENUM('O', 'B', 'C'), defaultValue: 'O' },
    closedAt: { type: DataTypes.DATE, allowNull: true },
    deletedBy: { type: DataTypes.INTEGER, allowNull: true },
    closedBy: { type: DataTypes.INTEGER, allowNull: true },
    severedAt:  {type: DataTypes.DATE, allowNull: true },
    lastActivity:  {type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
      close: function(user_id)
      {
        this.state = 'C';
        this.closedAt = new Date();
        this.closedBy = user_id;
      },
      block: function(user_id)
      {
        this.state = 'B';
        this.severedAt = new Date();
        this.deletedBy = user_id;
      }
    },
      classMethods:{
        associate: function(models) {
          Channel.belongsTo(models.Project);
          Channel.belongsToMany(models.User, { through: models.ChannelUser });
          Channel.hasMany(models.Call);
        },
        nameLength: function(){
          return 50;
        },
        descriptionLength: function(){
          return 200;
        }
      },
      indexes:[{
        name: 'channel_project_idx',
        method: 'BTREE',
        fields: ['ProjectId']
      }]
    }
  );

  return Channel;
};
