"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var GithubIntegration = sequelize.define("GithubIntegration", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(50) },
    token: { type: DataTypes.STRING(50) }
  }, {
    instanceMethods: {
    },
      classMethods:{
        associate: function(models) {
          GithubIntegration.belongsTo(models.ProjectIntegration, { as: 'ProjectIntegration' } );
          GithubIntegration.belongsTo(models.Channel);
        }
      }
    }
  );

  return GithubIntegration;
};
