"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var Integration = sequelize.define("Integration", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(50) },
    description: { type: DataTypes.STRING(500) },
    active: { type: DataTypes.BOOLEAN, defaultValue: true }
  }, {
    instanceMethods: {
    },
      classMethods:{
        nameMaxLength: function(){
          return 50;
        },
        nameMinLength: function(){
          return 2;
        },
        descriptionLength: function(){
          return 500;
        }
      }
    }
  );

  return Integration;
};
