"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var MessageType = sequelize.define("MessageType", {
    // id autogenerated by sequelize
    description: { type: DataTypes.STRING(30) },
    character: { type: DataTypes.CHAR(2), defaultValue: 'T' }
  }, {
      classMethods:{
        associate: function(models) {
          MessageType.hasMany(models.Message);
        }
      }
    }
  );

  return MessageType;
};
