"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var PrivateMessage = sequelize.define("PrivateMessage", {
    // id autogenerated by sequelize
    content: { type: DataTypes.STRING(500) },
    channel: { type: DataTypes.STRING(50) },
    sentDateTimeUTC: { type: DataTypes.DATE, allowNull: false, defaultValue: new Date() },
    //DestinationUserId: { type: DataTypes.INTEGER },
  }, {
      classMethods:{
        associate: function(models) {
          PrivateMessage.belongsTo(models.User,  { as: 'OriginUser' });
          PrivateMessage.belongsTo(models.User,  { as: 'DestinationUser' });
          PrivateMessage.belongsTo(models.MessageType);
        }
      }
    }
  );

  return PrivateMessage;
};
