"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var ProjectUser = sequelize.define("ProjectUser", {
    // id autogenerated by sequelize
    isOwner: { type: DataTypes.BOOLEAN, defaultValue: false },
    active: { type: DataTypes.BOOLEAN, defaultValue: true },
    severedAt: { type: DataTypes.DATE, allowNull: true },
    disconnectedAt: { type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
      disconnect: function()
      {
        this.disconnectedAt = new Date();
      }
    },
      classMethods:{

      }
    }
  );

  return ProjectUser;
};
