"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var Project = sequelize.define("Project", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(40) },
    description: { type: DataTypes.STRING(200) },
    state: { type: DataTypes.ENUM('O', 'B', 'C'), defaultValue: 'O' },
    closedAt: { type: DataTypes.DATE, allowNull: true },
    severedAt: { type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
      close: function()
      {
        this.state = 'C';
        this.closedAt = new Date();
      },
      block: function()
      {
        this.state = 'B';
        this.severedAt = new Date();
      }
    },
      classMethods:{
        associate: function(models) {
          Project.belongsToMany(models.User, { through: models.ProjectUser });
          Project.belongsToMany(models.Integration, { through: models.ProjectIntegration });
        }
      },
      indexes:[{
        name: 'project_idx',
        method: 'BTREE',
        fields: ['id']
      }]
    }
  );

  return Project;
};
