"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var ProjectIntegration = sequelize.define("ProjectIntegration", {
    // id autogenerated by sequelize
    active: { type: DataTypes.BOOLEAN, defaultValue: true }
  }, {
    instanceMethods: {

    },
      classMethods:{

      }
    }
  );

  return ProjectIntegration;
};
