"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var ProjectUser = sequelize.define("ProjectUser", {
    // id autogenerated by sequelize
    isOwner: { type: DataTypes.BOOLEAN, defaultValue: false },
    active: { type: DataTypes.BOOLEAN, defaultValue: true },
    severedAt: { type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
    },
      classMethods:{/*
        associate: function(models) {
          ProjectUser.belongsTo(models.User, {
            onDelete: "CASCADE",
            foreignKey: {
              allowNull: false
            }
          });
          ProjectUser.belongsTo(models.Project, {
            onDelete: "CASCADE",
            foreignKey: {
              allowNull: false
            }
          });
        }
      */}
    }
  );

  return ProjectUser;
};
