"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var Project = sequelize.define("Project", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(40) },
    description: { type: DataTypes.STRING(2000) },
    state: { type: DataTypes.ENUM('A', 'B', 'C'), defaultValue: 'A' },
    closedAt: { type: DataTypes.DATE, allowNull: true },
    severedAt: { type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
      close: function()
      {
        this.state = 'C';
        this.closedAt = new Date();
      },
      block: function()
      {
        this.state = 'B';
        this.severedAt = new Date();
      },
      isOwner: function(user)
      {
        //this.owner == user.id;
      },
      isMember: function(user)
      {
        //this.getUsers({ where: ['id = ?', user.id] }).then(function(users){
          //if (users === undefined || users.length === 0)
          //  return false;

          //return true;
        //});
      },
      populateProjectRecord: function(name, description){
          //setting name
          this.name = name;

          //setting description
          this.description = description;
      },
      canSee: function(user){
        //return (this.isOwner(user) || this.isMember(user));
      }
    },
      classMethods:{
        associate: function(models) {
          Project.belongsToMany(models.User, { through: models.ProjectUser });
        }
      }
    }
  );

  return Project;
};
