"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var TrelloIntegration = sequelize.define("StatusCakeIntegration", {
    // id autogenerated by sequelize
    name: { type: DataTypes.STRING(50) },
    token: { type: DataTypes.STRING(50) },
    cakeUser: { type: DataTypes.STRING(50) },
    cakeToken: { type: DataTypes.STRING(200) },
    active: { type: DataTypes.BOOLEAN, defaultValue: true }
  }, {
    instanceMethods: {
    },
      classMethods:{
        associate: function(models) {
          TrelloIntegration.belongsTo(models.ProjectIntegration, { as: 'ProjectIntegration' } );
          TrelloIntegration.belongsTo(models.Channel);
        }
      }
    }
  );

  return TrelloIntegration;
};
