"use strict";

/**

 * Module dependencies

 */

module.exports = function(sequelize, DataTypes) {
  var Token = sequelize.define("Token", {
    // id autogenerated by sequelize
    value: { type: DataTypes.STRING(2000)  }
  },
  {
    classMethods: {
      associate: function(models) {
        Token.belongsTo(models.User, {
          onDelete: "CASCADE",
          foreignKey: {
            allowNull: false
          }
        });
      }
    }
  });
  return Token;
};
