"use strict";

/**

 * Module dependencies

 */

var crypto = require('crypto');
var jwt = require('jsonwebtoken');

module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("User", {
    // id autogenerated by sequelize
    email: { type: DataTypes.STRING, unique: true, validate: { isEmail: true } },
    hash: { type: DataTypes.STRING },
    salt: { type: DataTypes.STRING },
    lastName: { type: DataTypes.STRING },
    firstName: { type: DataTypes.STRING },
    alias: { type: DataTypes.STRING },
    profilePicture: { type: DataTypes.STRING, allowNull: true },
    confirmed:  { type: DataTypes.BOOLEAN, defaultValue: false },
    isAdministrator:  { type: DataTypes.BOOLEAN, defaultValue: false },
    active: { type: DataTypes.BOOLEAN, defaultValue: true },
    severedAt: { type: DataTypes.DATE, allowNull: true }
  }, {
    instanceMethods: {
      setPassword: function(password){
        this.setDataValue('salt', crypto.randomBytes(16).toString('hex'));
        this.setDataValue('hash', crypto.pbkdf2Sync(password, this.salt, 1000, 64).toString('hex'));
      },
      validatePassword: function(password)
      {
           var hash = crypto.pbkdf2Sync(password, this.salt, 1000, 64).toString('hex');
           return this.hash === hash;
      },
      generateJWT: function() {
        // expirates in 30 days
        var today = new Date();
        var expiration = new Date(today);
        expiration.setDate(today.getDate() + 30);

        return jwt.sign({
            _id: this.id,
            email: this.email,
            alias: this.alias,
            exp: parseInt(expiration.getTime() / 1000)}, 'mySecretPassword');
      }
    }
  });

  return User;
};
